<!-- build:js ../js/common.js -->
<script src="../js/jquery.js"></script>
<script src="../js/common.js"></script>
<!-- endbuild -->

<!-- build:js ../js/vendor.js -->
<script src="../vendor/remodal.js"></script>
<script src="../vendor/slick.js"></script>
<script src="../vendor/highlight.pack.js"></script>
<script src="../vendor/highlightjs-line-numbers.js"></script>
<!-- endbuild -->

<script>
hljs.initHighlightingOnLoad();
hljs.initLineNumbersOnLoad({
            singleLine: true
        });
</script>