<!doctype html>
<html lang="ko">
<head>
	<meta charset="utf-8">
	<meta name="description" content="홈페이지 구축 혹은 운영 프로젝트에서 퍼블리싱을 보다 더 쉽게하기 위한 인덱스 페이지" />
	<meta name="author" content="UI Lab">
	<meta name="keywords" content="html,html5,css,css3,javascript,jquery,mobile app,웹표준,웹퍼블리싱,웹퍼블리셔,웹접근성,frontend developer,ui개발,워드프레스" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link rel="stylesheet" href="../css/global.css" />
    <link rel="stylesheet" href="../css/icon.css" />
    <title>@@if (context.projectName) {@@projectName} | Index</title>
</head>