  <!-- desktop & tablet -->
  <header class="header">
    <a href="../index.html" class="header__link">
      <img src="//ui-lab.co.kr/wp-content/uploads/2016/07/HUILab_logo_H100.png" alt="UI Lab" class="header__image"/>
      <h1 class="header__title">L I B R A R Y</h1>
    </a>

    <div class="header__contact">
      <a class="header__link tel" href="tel:070-4112-1012">
        <i class="fas fa-phone"></i>
        <span class="hidden">전화</span>
      </a>
      <a class="header__link mail" href="mailto:jhlee@ui-lab.co.kr?cc=yjkim@ui-lab.co.kr,yhpark@ui-lab.co.kr&subject=[UI Lab]%20문의&body=안녕하세요,%20문의%20사항이%20있습니다.">
        <i class="far fa-envelope"></i>
        <span class="hidden">메일</span>
      </a>
    </div>
  </header>

  <aside class="aside">
    <nav class="gnb">
      <h2 class="gnb__title">COMPONENTS</h2>
      <a class="gnb__item" href="headline.html" target="_self">headline</a>
      <a class="gnb__item" href="button.html" target="_self">button</a>
      <a class="gnb__item" href="input.html" target="_self">input</a>
      <a class="gnb__item" href="pagination.html" target="_self">pagination</a>
      <a class="gnb__item" href="tabs.html" target="_self">tabs</a>
      <a class="gnb__item" href="modal.html" target="_self">modal</a>
      <a class="gnb__item" href="accordion.html" target="_self">accordion</a>
      <a class="gnb__item" href="dropdown.html" target="_self">dropdown</a>
      <a class="gnb__item" href="slider.html" target="_self">slider</a>
    </nav>
  </aside>
  <!-- //desktop & tablet -->

  <!-- mobile -->
  <header class="header header--mobile">
    <a href="#" class="header__link" data-js="aside__toggle">
      <i class="fas fa-bars fa-2x"></i>
      <span class="hidden">메뉴</span>
    </a>

    <div class="header__contact">
      <a class="header__link" href="tel:070-4112-1012">
        <i class="fas fa-phone fa-2x"></i>
        <span class="hidden">전화</span>
      </a>
      <a class="header__link" href="mailto:jhlee@ui-lab.co.kr?cc=yjkim@ui-lab.co.kr,yhpark@ui-lab.co.kr&subject=[UI Lab]%20문의&body=안녕하세요,%20문의%20사항이%20있습니다.">
        <i class="far fa-envelope fa-2x"></i>
        <span class="hidden">메일</span>
      </a>
    </div>

    <aside class="aside aside--mobile">
      <nav class="gnb">
      <h2 class="gnb__title">COMPONENTS</h2>
        <a class="gnb__item" href="headline.html" target="_self">headline</a>
        <a class="gnb__item" href="button.html" target="_self">button</a>
        <a class="gnb__item" href="input.html" target="_self">input</a>
        <a class="gnb__item" href="pagination.html" target="_self">pagination</a>
        <a class="gnb__item" href="tabs.html" target="_self">tabs</a>
        <a class="gnb__item" href="modal.html" target="_self">modal</a>
        <a class="gnb__item" href="accordion.html" target="_self">accordion</a>
        <a class="gnb__item" href="dropdown.html" target="_self">dropdown</a>
        <a class="gnb__item" href="slider.html" target="_self">slider</a>
      </nav>
    </aside>
  </header>
  <!-- //mobile -->